language: node_js
sudo: false
node_js:
- node

matrix:
  include:
  - os: osx
    env: COMPILER=clang++
    osx_image: xcode9.2
    compiler: clang
  - os: linux
    env: CXX=clang-3.6
    compiler: clang-3.6

deploy:
  provider: script
  script: npm run pre-build && npm run pre-build:upload -u ${PREBUILD_UPLOAD}
  api_key:
    secure: T8tIxptf3FpwTyy2SSaBP3VFEAnJjfzD9B81UW62a/ZOM10f5w8IX9VmYfWvQB16q3ezlzHj75EYELkZNTbzlETCQbvdqqIlrTyPAwpFk8MlQw9GxZe/lcXvkboJf4eZCYMnwd3vkuWjGMkMX88l2YLvgnv8V490U87zhGw+2qnxUPNcXS+2Ncbu9Q2POLoWMQ1PBJw7qpYSvu2io6LjiBJwSzIxzn73nCu6O9uQGQNiq7UQECer6oImr8tJD6Bxa58bEbJrHWESzW6zju12GLnxFg5192j1iez1ZfT9gCrYwPntdKvzrge1jqdVRyWx9StdKTWJob/zChtGQMBbQgvOfD3/QTaRCnFWtVaHq/C/Jr87UqNrINCy8NGMUu+4B4qtBm+aAql01O1rvUJhgkqhIuq1ol+JeEnxLqBkxK002Fro+7/E+2o5oHAE/Iu1kIt8X8s1fEXXXWz9YhID9Xyu91YuOEO6sUi4UdZxr4XP4PmkYid+LjItfOT5e5g1dSbaRBsYvQQ7GGqSkcmydRhjZQCWK43sdUnPb3qJwiEjRiJMcCcc+FxVIZg0YmrVNMeXDlEvQcHli8kGg9ENwSjSF3H+VOYU4Y/g0UU5KQqW4iAZ0b9EZ2NRAgZIvHkH4QD+iVHLDWz9++Q1fvm4JVf2gLxa/hevW20ifP0C3e4=
  on:
    repo: Aerijo/tree-sitter-biber
