language: node_js
sudo: false
node_js:
- node
matrix:
  include:
  - os: osx
    env: COMPILER=clang++
    osx_image: xcode9.2
    compiler: clang
  - os: linux
    env: CXX=clang-3.6
    compiler: clang-3.6
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
env:
  global:
    secure: h/uhGd2N7PumZzqnPta0wBZkNUJyaemdv3XpGrBYhVlDgnB6sCDk4OusAArEc6HWXYNgS8cUbhMfLmQkDadxDjMocRdNV/QTJUKM2L7aD6Cw+vweet9C8Xfm76AIlefUBFq1boOCKW6+kBwiW4451yb0xTVfZpBcDisxkrH4YWFZH4FfRUEnRvzdtfaB/Vb3l4KOTvXIVEb7Wa3E09H8AMyf5JsOYYXNMJGL69Z9KI3gTGz/63cP5xNwp1V5IBVamobladZy40Ec60o48HL2+2U1xjVaM/rimqb9ouQdWQpIN8sRUL95K8Imi90Z1LD5kO0wfyeJmIaEaAl2Va63xmYJC2h29WdQsS6uhvveJFOGN3kJqsx3f8fnpcGh5fnTLK7qrFr5NhrsKWkU0Mlfdm+/0UAYx3KcyVsJdsa6FdYY0X6tQbhOcGM5bTNTmYbionBgVwFCntakq64PnOYfTAmDwgnwlWOd8ssrRkhWavPNrlViiX0ozopUf3SpKv4eMWCB1jc3B9xqw3S4rHrtpQPhnUJzVX2F382J5y70lMcLmOJUYnHWae4eU9bq5aVG4H05MWaGjH6ita02KcpoeoIx2B7+q119imt7VW6j2xme6zFVfhTXmivskFhK0Pr4VgRGRG+fd/m173sPAHLoVsWIgI9ErX7edwEtUdzqZ8A=
deploy:
  provider: script
  script: npm run pre-build && npm run pre-build:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  api_key:
    secure: JlvPkIt7aV2tVxHhGPqMo2XBSmduu9Yh4eCpNfxojMVtbo0Jw2JZFYCI0LTwfLpvk14bUpGTTBFvogQ2XQaPXbBMdMLew6LdkYvpyDw07IPvNzsOK2kjFmJ4UT5SROsK0VVo1FNmbJQpOhQNWj5PyS5aSAHS+RswOT/KoP+Eq32HEgyAXrdRP3HUbP9UQqpSixavEVKP0eNd5H3iYc/4ddDjWuwJSWbAvbMUtTsjHEcdFTvAfXZIPxghKcDNhE2Td/B+ho0lw2d4TutdWVP1/s9ssiSwgvxQ4kiMPOLoS4YviATVK2C5uJF2H8Z4ChOZw4ggY8/lc+5AleOB++B2pvNnQMoWjkpIUPd51bP2leqan28jcP06Hw9mEucD1SihmdkJQFIXJgXUNWYQouQBiAoF1rfIYUfANrrXGsRW8DfVtB+RyZBTNlDdLEav4Q1QpUePnTQpg5lMuVvz+CzdJsIYhqgeqcO/y6uHGxh4TrFHkypnQkC7ucIRjlchoYCK87+mdwHUe+Rd4RjZKaLjVyAXqQ8Ff0retfVpJgTHtMWy4TkYnD/EFPssjPoxMaUoiinEeDDrxBRuXMhX0iJ+7ZyAVaHrjaBBFuGvFIY+3plmE/0bHzO8I5n8UFdwYDGapVkRHufg+17PyVCmHbHt2Q3gkn1WEv4wlj89J6PA2vw=
  on:
    all_branches: true
    tags: true
