image: Visual Studio 2015

environment:
  NODEJS_VERSION: "8"
  PREBUILD_UPLOAD:
    secure: jxeNZt+6zbeotHubwm6t5umnhJ33uRCKYOoNz3F1MmzvOateq0rcfbC5HkTW1BRI

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run test

build: off

branches:
  only:
    - master
    - /^v.*$/

deploy_script: npm run pre-build && npm run pre-build:upload -u %PREBUILD_UPLOAD%
