image: Visual Studio 2015
version: "{build}"
build: off
skip_tags: true

environment:
  NODEJS_VERSION: "8"
  PREBUILD_UPLOAD:
    secure: jxeNZt+6zbeotHubwm6t5umnhJ33uRCKYOoNz3F1MmzvOateq0rcfbC5HkTW1BRI

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:platform
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm i

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)
